### ISSUE TITLE
feat: add demo screenshot to readme

### ISSUE THREAD

**Issue by dargmuesli** [DerYeger/finwa-legacy#12]
So that interested users can see what the gui is like to get a quick idea what this tool is/will be capable of 🖼

**Comment by DerYeger** [comment]
Thanks for the suggestion. I'll add screenshots once the basic functionality is implemented. 👍🏻

**Comment by DerYeger** [comment]
This project has been abandoned and replaced by https://github.com/DerYeger/finwa.
You may find screenshots [here](https://jan-mueller.at/projects/finwa) or check it out at https://finwa.yeger.eu, no login required!

**Comment by dargmuesli** [comment]
Thanks for the update!
